sudo: required

services:
  - docker

before_install:
  - docker build -t sarahsga4/react-test -f ./client/Dockerfile.dev ./client

script: 'true'

after_success:
  - docker build -t sarahsga4/multi-client ./client
  - docker build -t sarahsga4/multi-nginx ./nginx
  - docker build -t sarahsga4/multi-server ./server
  - docker build -t sarahsga4/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push sarahsga4/multi-client
  - docker push sarahsga4/multi-nginx
  - docker push sarahsga4/multi-server
  - docker push sarahsga4/multi-worker